[package]
name = "luauencrypt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chacha20poly1305 = "0.10"
clap = { version = "4.5", features = ["derive"] }
libc = "0.2"
rand = "0.9"

[build-dependencies]
luau_build = { package = "luau0-src", version = "0.15" }
