[package]
name = "luauencrypt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
chacha20poly1305 = "0.10.1"
clap = { version = "4.5.47", features = ["derive"] }
hex = "0.4.3"
libc = "0.2"
rand = "0.9.2"

[build-dependencies]
luau0-src = "0.15.7"
